Improve
mfrank37/cxx-hello-world pull request #1
Opened 2022-07-24 13:21 UTC by MayankLakhotia

code work faster

2022-07-24 13:22 UTC, MayankLakhotia commented
code work faster and take less space

2022-07-24 16:46 UTC, mfrank37 commented
Hi @MayankLakhotia ,
Thanks for your will to contribute, welcome.

I agree the `endl` isn't necessary. Your code is spacious and harder to read. 
Also you shouldn't remove the `!` exclamation from the message.

```code work faster and take less space``` by you. I don't see how your changes do this.

2022-07-24 16:49 UTC, mfrank37 commented on hello.cpp
> +
extra space

2022-07-24 16:49 UTC, mfrank37 commented on hello.cpp
> +
extra space

2022-07-24 16:50 UTC, mfrank37 commented on hello.cpp
> +
extra space unnecessary.

2022-07-24 16:50 UTC, mfrank37 commented on hello.cpp
> +
extra space unnecessary.

2022-07-24 16:52 UTC, mfrank37 commented on hello.cpp
> +    cout << "Hello World";
missing `!` from the message.

2022-07-24 16:52 UTC, mfrank37 requested changes
Needs more readable code, and `!`

2022-08-07 14:59 UTC, closed without merging

2022-10-11 07:11 UTC, MayankLakhotia commented
Bro I am just trying pull request

On Sun, Aug 7, 2022, 8:29 PM mfrank37 ***@***.***> wrote:

> Closed #1 <https://github.com/mfrank37/cxx-hello-world/pull/1>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mfrank37/cxx-hello-world/pull/1#event-7142332172>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APVKRN66UKIMMZKJURVPKIDVX7FNLANCNFSM54PVDS5Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>